version: 2.0

static_analysis: &static_analysis
  run:
    name: Static Analysis
    command: ./gradlew ktlintCheck lintDebug

unit_test: &unit_test
  run:
    name: Unit Tests
    command: ./gradlew testDebugUnitTest

jobs:
  build:
    working_directory: ~/shapes
    docker:
      - image: circleci/android:api-29

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - <<: *static_analysis
      - <<: *unit_test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
